/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author guima
 */
public class AlterarConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form MarcaConsulta
     */
    public AlterarConsulta() {
        initComponents();
        redimensionar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        l2 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Paciente :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 140, 30);
        getContentPane().add(t1);
        t1.setBounds(450, 20, 190, 30);

        jLabel2.setText("Nome do Paciente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 60, 140, 30);
        getContentPane().add(t2);
        t2.setBounds(450, 60, 190, 30);

        jLabel3.setText("Data da consulta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 110, 90, 20);

        jLabel6.setText("Horas da Consulta");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 150, 90, 20);

        jLabel8.setText("Idade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 180, 50, 30);
        getContentPane().add(t3);
        t3.setBounds(450, 180, 190, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Plano de saude Particular"));
        jPanel1.setLayout(null);

        jLabel9.setText("Plano de saude ou Particular");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 190, 240, 30);

        buttonGroup1.add(r2);
        r2.setText("Particular");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2);
        r2.setBounds(20, 60, 140, 23);

        buttonGroup1.add(r1);
        r1.setText("Plano de saude");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(20, 20, 140, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 220, 200, 110);

        l2.setBorder(javax.swing.BorderFactory.createTitledBorder("Medico"));
        l2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        l2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                l2ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(l2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(710, 190, 140, 150);

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Especialidade"));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(710, 20, 140, 150);

        jButton1.setText("Alterar Consulta ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 380, 140, 40);

        t4.setText("ex:25/02/2020");
        getContentPane().add(t4);
        t4.setBounds(450, 100, 190, 30);

        t5.setText("ex:10:50");
        getContentPane().add(t5);
        t5.setBounds(450, 140, 190, 30);

        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 350, 70, 20);
        getContentPane().add(l1);
        l1.setBounds(400, 330, 80, 20);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents
String especialidade="";
String nomeMedico="";
String tipos="";
float valor=0f;
ClinicaDao c = new ClinicaDao();
    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        especialidade = jList2.getSelectedValue();
        if(r1.isSelected()){
            
            l1.setText(""+0);
        }
        else if(r2.isSelected()){
            
            valor = c.valores(especialidade);
            l1.setText(""+valor);
        }
        listaTodos5();
        
    }//GEN-LAST:event_jList2ValueChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        listaTodos();
        listaTodos2();
    }//GEN-LAST:event_formInternalFrameOpened

    private void l2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_l2ValueChanged
        nomeMedico = l2.getSelectedValue();
    }//GEN-LAST:event_l2ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rg = t1.getText();
        String nome  = t2.getText();
        String idade = t3.getText();
        String data  = t4.getText();
        String horas = t5.getText();
        if(r1.isSelected()){
        tipos="Plano de saude";
        }
        else if(r2.isSelected()){
        tipos="Particular";
        }
        valor=Float.parseFloat(l1.getText());
                                ClinicaDao D = new ClinicaDao();
                                Consulta d =new Consulta(rg,nome,data,horas,idade,tipos,especialidade,nomeMedico,valor,0);
                            String resp = D.updateConsulta(d);
                            if(resp == "ok"){
                            JOptionPane.showMessageDialog(null, "Dados foram atualizados");
                            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        if(r2.isSelected()){
            
            valor = c.valores(especialidade);
            System.out.print(valor+"");
            l1.setText(""+valor);
        }
    }//GEN-LAST:event_r2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        if(r1.isSelected()){
            
            
            l1.setText(""+0);
        }
    }//GEN-LAST:event_r1ActionPerformed
public void listaTodos() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc();
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addElement(lista.get(i).getEspecialidade());
        }
        jList2.setModel(modelo);
    }
public void listaTodos2() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc2();
        DefaultListModel modelo2 = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo2.addElement(lista.get(i).getNome());
        }
        l2.setModel(modelo2);
    }
public void listaTodos5() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc5(especialidade);
        DefaultListModel modelo4 = new DefaultListModel();

        for (int i = 0; i < lista.size(); i++) {
            modelo4.addElement(lista.get(i).getNome());
        }
        l2.setModel(modelo4);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JList<String> l2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables

    private void redimensionar() {
       Toolkit t = Toolkit.getDefaultToolkit();
        Dimension dimensao = t.getScreenSize();
        
        if(dimensao.width ==800 && dimensao.height == 600){
            jScrollPane1.setBounds(110, 190, 140, 150);
            jScrollPane2.setBounds(110, 20, 140, 150);   
        }
    }
}
