/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author guima
 */
public class Alterar_Funcionario1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cad_Dados_Paciente
     */
    public Alterar_Funcionario1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Funcionario :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 110, 180, 30);
        getContentPane().add(t1);
        t1.setBounds(550, 110, 190, 30);

        jLabel2.setText("Nome do Funcionario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 150, 170, 30);
        getContentPane().add(t2);
        t2.setBounds(550, 150, 190, 30);

        jButton1.setText("Alterar Status Funcionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 460, 180, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" cargo"));
        jPanel2.setLayout(null);

        jLabel14.setText("Plano de saude ou Particular");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 190, 240, 30);

        buttonGroup1.add(r3);
        r3.setText("Demitido");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel2.add(r3);
        r3.setBounds(20, 30, 140, 23);

        buttonGroup1.add(r4);
        r4.setText("Contratado");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        jPanel2.add(r4);
        r4.setBounds(20, 60, 140, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(450, 210, 270, 120);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String resp="";
        String rg=t1.getText();
       String nome=t2.getText();
       ClinicaDao c= new ClinicaDao();
       if(r3.isSelected()){
        resp = c.updateStatus(rg, nome,"Demitido");
       }
       if(r4.isSelected()){
       resp = c.updateStatus(rg, nome,"Contratado");
       }
        if(resp == "ok"){
                            JOptionPane.showMessageDialog(null, "Funcionario Alterado");
                            }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        
        
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
       

    }//GEN-LAST:event_r4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
