/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author guima
 */
public class Bate_Ponto_saida extends javax.swing.JInternalFrame {

    /**
     * Creates new form Bate_Ponto_saida
     */
    public Bate_Ponto_saida() {
        redimensionar();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt2 = new javax.swing.JTextField();
        jt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 90, 110, 30);

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 110, 30);
        getContentPane().add(jt2);
        jt2.setBounds(140, 90, 220, 30);
        getContentPane().add(jt1);
        jt1.setBounds(140, 40, 230, 30);

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 170, 63, 23);

        setBounds(0, 0, 525, 347);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClinicaDao c= new ClinicaDao();
        String valor = new String(jt2.getText());
        java.util.Date data = new java.util.Date();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(data.getTime());
            
        boolean resposta = c.consultarr(jt1.getText(), valor);
        if (resposta == true) {
            JOptionPane.showMessageDialog(this, "tchau ");
            Entrada_Saida e=new Entrada_Saida(jt1.getText(),timestamp);
            c.gravarSaida(e);
            System.exit(0);
        } 
        else {
            JOptionPane.showMessageDialog(this, "Acesso Negado ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    // End of variables declaration//GEN-END:variables

    private void redimensionar() {
        
    }
}
