/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Cad_Dados_Paciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cad_Dados_Paciente
     */
    public Cad_Dados_Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t5 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Medico = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Paciente :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 70, 140, 30);
        getContentPane().add(t1);
        t1.setBounds(300, 70, 190, 30);

        jLabel2.setText("Nome do Paciente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 110, 140, 30);
        getContentPane().add(t2);
        t2.setBounds(300, 110, 190, 30);

        jLabel8.setText("Idade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 150, 140, 30);
        getContentPane().add(t3);
        t3.setBounds(300, 150, 190, 30);

        t4.setColumns(20);
        t4.setRows(5);
        jScrollPane1.setViewportView(t4);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 190, 240, 90);

        jLabel9.setText("Alergias");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 220, 110, 30);

        t5.setColumns(20);
        t5.setRows(5);
        jScrollPane2.setViewportView(t5);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(270, 290, 240, 90);

        jLabel10.setText("Descrição Medica");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 320, 110, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanel1.setLayout(null);

        jLabel11.setText("Plano de saude ou Particular");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 190, 240, 30);

        buttonGroup1.add(r2);
        r2.setText("Feminino");
        jPanel1.add(r2);
        r2.setBounds(20, 60, 140, 23);

        buttonGroup1.add(r1);
        r1.setText("Masculino ");
        jPanel1.add(r1);
        r1.setBounds(20, 30, 140, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(560, 80, 200, 110);

        jButton1.setText("Cadastrar Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 410, 180, 30);

        jLabel3.setText("Possiveis Doença");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 210, 100, 20);
        getContentPane().add(t6);
        t6.setBounds(650, 210, 200, 30);

        Medico.setBorder(javax.swing.BorderFactory.createTitledBorder("Medico"));
        Medico.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Medico.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MedicoValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(Medico);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(750, 250, 140, 150);

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Especialidade"));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(jList2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(580, 250, 140, 150);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents
String sexo="";
String especialidade="";
String medico="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rg=t1.getText();
        String nome=t2.getText();
        String idade=t3.getText();
        String alergia=t4.getText();
        String descricao=t5.getText();
        String diagnostico=t6.getText();
        if(r1.isSelected()){
        sexo="Masculino";
        }
        else if(r2.isSelected()){
        sexo="Feminino";
        }
        ClinicaDao c= new ClinicaDao();
        Paciente p= new Paciente(rg,nome,idade,alergia,descricao,diagnostico,sexo,medico,especialidade);
        String resp =c.gravap(p);
        if(resp == "ok"){
                            JOptionPane.showMessageDialog(null, "Dados foram cadastrados");
                            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MedicoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MedicoValueChanged
        medico = Medico.getSelectedValue();
        
    }//GEN-LAST:event_MedicoValueChanged

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        especialidade = jList2.getSelectedValue();
        listaTodos5();
        
    }//GEN-LAST:event_jList2ValueChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
          listaTodos();
        listaTodos2();
    }//GEN-LAST:event_formInternalFrameOpened
public void listaTodos() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc();
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addElement(lista.get(i).getEspecialidade());
        }
        jList2.setModel(modelo);
    }
public void listaTodos2() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc2();
        DefaultListModel modelo2 = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo2.addElement(lista.get(i).getNome());
        }
        Medico.setModel(modelo2);
    }
public void listaTodos5() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc5(especialidade);
        DefaultListModel modelo4 = new DefaultListModel();

        for (int i = 0; i < lista.size(); i++) {
            modelo4.addElement(lista.get(i).getNome());
        }
        Medico.setModel(modelo4);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Medico;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTextArea t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
