/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import javax.swing.JOptionPane;

/**
 *
 * @author guima
 */
public class Cad_espec_medico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cad_Dados_Paciente
     */
    public Cad_espec_medico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("Especialidade");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 120, 100, 30);
        getContentPane().add(t1);
        t1.setBounds(560, 120, 190, 30);

        jLabel2.setText("Valor da consulta:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 170, 90, 30);
        getContentPane().add(t2);
        t2.setBounds(560, 170, 190, 30);

        jButton1.setText("Cadastrar Novo produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 280, 180, 30);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String espec=t1.getText();
        float valor=Float.parseFloat(t2.getText());
        ClinicaDao c= new ClinicaDao();
       String resp =  c.gravae(espec, valor);
       if(resp == "ok"){
                            JOptionPane.showMessageDialog(null, "Dados foram Cadastrados");
                            }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
