/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import javax.swing.JOptionPane;

/**
 *
 * @author guima
 */
public class Cad_Produto_estoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cad_Dados_Paciente
     */
    public Cad_Produto_estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("ID do produto:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 80, 100, 30);
        getContentPane().add(t1);
        t1.setBounds(550, 80, 190, 30);

        jLabel2.setText("Nome do Produto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 130, 150, 30);
        getContentPane().add(t2);
        t2.setBounds(550, 130, 190, 30);

        jLabel8.setText("Categoria:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 180, 60, 20);

        jButton1.setText("Cadastrar Novo produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 240, 210, 30);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico", "Alimenticio", "Limpeza" }));
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(560, 180, 170, 20);

        setBounds(0, 0, 1365, 768);
    }// </editor-fold>//GEN-END:initComponents
    String categoria="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=t1.getText();
        String nome=t2.getText();
        
        ClinicaDao c = new  ClinicaDao();
        String resp = c.gravaprodu(id, nome, categoria);
        c.gravaestoque(id, nome, categoria,0);
        if(resp == "ok"){
                            JOptionPane.showMessageDialog(null, "Dados foram cadastrados");
                            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        categoria = (String) c1.getSelectedItem();
    }//GEN-LAST:event_c1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
