/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author guima
 */
public class Cad_Dados_Funcionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cad_Dados_Paciente
     */
    public Cad_Dados_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        r5 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Funcionario :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 60, 180, 30);
        getContentPane().add(t1);
        t1.setBounds(420, 60, 190, 30);

        jLabel2.setText("Nome do Funcionario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 100, 170, 30);
        getContentPane().add(t2);
        t2.setBounds(410, 100, 190, 30);

        jLabel8.setText("Idade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 140, 170, 30);
        getContentPane().add(t3);
        t3.setBounds(410, 140, 190, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanel1.setLayout(null);

        jLabel11.setText("Plano de saude ou Particular");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 190, 240, 30);

        buttonGroup1.add(r2);
        r2.setText("Feminino");
        jPanel1.add(r2);
        r2.setBounds(20, 60, 140, 23);

        buttonGroup1.add(r1);
        r1.setText("Masculino ");
        jPanel1.add(r1);
        r1.setBounds(20, 30, 140, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(640, 70, 200, 110);

        jButton1.setText("Cadastrar Funcionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 460, 180, 30);

        jLabel4.setText("Loguin Do Funcionario :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 180, 170, 30);
        getContentPane().add(t4);
        t4.setBounds(410, 180, 190, 30);

        jLabel5.setText("Senha do Funcionario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 220, 160, 30);
        getContentPane().add(t5);
        t5.setBounds(410, 220, 190, 30);

        jLabel12.setText("Salario:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 260, 150, 30);
        getContentPane().add(t6);
        t6.setBounds(410, 260, 190, 30);

        jLabel6.setText("EMAIL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 300, 150, 30);
        getContentPane().add(t7);
        t7.setBounds(410, 300, 190, 30);

        jLabel7.setText("Numero FIXO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(260, 340, 150, 30);
        getContentPane().add(t8);
        t8.setBounds(410, 340, 190, 30);

        jLabel13.setText("Numero carteira de trabalho");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(260, 380, 150, 30);
        getContentPane().add(t9);
        t9.setBounds(410, 380, 190, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" cargo"));
        jPanel2.setLayout(null);

        jLabel14.setText("Plano de saude ou Particular");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 190, 240, 30);

        buttonGroup2.add(r5);
        r5.setText("Gerente");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });
        jPanel2.add(r5);
        r5.setBounds(20, 90, 140, 23);

        buttonGroup2.add(r3);
        r3.setText("Atendente");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        jPanel2.add(r3);
        r3.setBounds(20, 30, 140, 23);

        buttonGroup2.add(r4);
        r4.setText("Medico");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        jPanel2.add(r4);
        r4.setBounds(20, 60, 140, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(640, 180, 270, 120);

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Especialidade"));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 310, 120, 140);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents
String sexo="";
String cargo="";
String especialidade;
String nomes="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String rg=t1.getText();
       String nome=t2.getText();
       String idade=t3.getText();
       String login=t4.getText();
       String senha=t5.getText();
       float salario=Float.parseFloat(t6.getText());
       String email=t7.getText();
       String numero=t8.getText();
       String numerocart=t9.getText();
       if(r1.isSelected()){
       sexo="Masculino";
       }
       else if(r2.isSelected()){
       sexo="Feminino";
       }
       if(r3.isSelected()){
       cargo="Atendente";
       
       }
       else if(r4.isSelected()){
       cargo="Medico";
       }
       else if(r5.isSelected()){
       cargo="Gerente";
       
       }
       Funcionario f = new Funcionario(rg,nome,idade,login,senha,salario,email,numero,numerocart,sexo,cargo,especialidade);
       ClinicaDao c= new ClinicaDao();
       String resp = c.gravaf(f,"Contratado");
        c.gravaes(especialidade,nome);
        if(resp == "ok"){
                            JOptionPane.showMessageDialog(null, "Funcionario cadastrado");
                            }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
       if(r3.isSelected()){
       jList1.setEnabled(false);
       especialidade=null;
       }
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        jList1.setEnabled(true);
        
    }//GEN-LAST:event_r4ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        if(r5.isSelected()){
       jList1.setEnabled(false);
       especialidade=null;
       }
    }//GEN-LAST:event_r5ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
       especialidade = jList1.getSelectedValue();
    }//GEN-LAST:event_jList1ValueChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        listaTodos();
    }//GEN-LAST:event_formInternalFrameOpened
public void listaTodos() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc13();
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addElement(lista.get(i).getEspecialidade());
        }
        jList1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
