/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Controle_Entrada_Saida_Funcionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Controle_Entrada_Saida_Funcionario
     */
    public Controle_Entrada_Saida_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        trix2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        trix1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        trix2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID funcionario", "Saida Funcionario"
            }
        ));
        jScrollPane3.setViewportView(trix2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(180, 200, 740, 110);

        trix1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID funcionario", "Entrada Funcionario"
            }
        ));
        jScrollPane4.setViewportView(trix1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(180, 70, 740, 110);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        listaTodo4();
        listaTodo5();
    }//GEN-LAST:event_formInternalFrameOpened
public void listaTodo4(){
         ArrayList <Entrada_Saida> lista=new ClinicaDao().listarFunc19();
         DefaultTableModel modelo=(DefaultTableModel)trix1.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getLogin(),lista.get(i).getDate()});
           
    }
         return; 
}
public void listaTodo5(){
         ArrayList <Entrada_Saida> lista=new ClinicaDao().listarFunc20();
         DefaultTableModel modelo=(DefaultTableModel)trix2.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
        modelo.addRow(new Object[]{lista.get(i).getLogin(),lista.get(i).getDate()});
            
    }
         return;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable trix1;
    private javax.swing.JTable trix2;
    // End of variables declaration//GEN-END:variables
}
