/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Controle_Financeiro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Controle_Entrada_Saida_Funcionario
     */
    public Controle_Financeiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        trix2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        trix1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        trix2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id produto", "Preco Compra ", "Nome Produto", "Quantidade Comprada", "Mes"
            }
        ));
        jScrollPane3.setViewportView(trix2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(190, 270, 730, 110);

        jLabel1.setText("RG Do Funcionario :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 50, 120, 30);
        getContentPane().add(t1);
        t1.setBounds(310, 50, 190, 30);

        trix1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RG", "Nome", "Idade", "Salario", "Email", "cargo"
            }
        ));
        jScrollPane4.setViewportView(trix1);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(180, 100, 730, 110);

        jLabel2.setText("Mes Da compra");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 230, 120, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(460, 230, 37, 20);

        jLabel3.setText("Total gasto no mes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 390, 150, 20);
        getContentPane().add(l1);
        l1.setBounds(320, 390, 210, 20);

        jButton1.setText("Mostrar Funcionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 50, 140, 23);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 230, 130, 23);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents
String mes ="";
float total = 0 ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String rg=t1.getText();
        listaTodos(rg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        listaTodo5();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       mes = (String) jComboBox1.getSelectedItem();
       
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listaTodo6(mes);
        ClinicaDao c = new ClinicaDao();
        float valor1,valor2,valor3;
        valor1=c.pegar2();
        valor2=c.pegar3(mes);
        valor3=c.pegar4();
        total=valor1+valor2-valor3;
        l1.setText(total+"");
    }//GEN-LAST:event_jButton2ActionPerformed
public void listaTodos(String Placa){
         ArrayList <Funcionario> lista=new ClinicaDao().listarFunc14(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix1.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getSalario(),lista.get(i).getEmail(),lista.get(i).getSexo(),lista.get(i).getCargo()});
            
    }}
public void listaTodo5(){
         ArrayList <Funcionario> lista=new ClinicaDao().listarFunc21();
         DefaultTableModel modelo=(DefaultTableModel)trix1.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getSalario(),lista.get(i).getEmail(),lista.get(i).getSexo(),lista.get(i).getCargo()});
            
    }}
public void listaTodo6(String mes){
         ArrayList <Produtos> lista=new ClinicaDao().listarFunc22(mes);
         DefaultTableModel modelo=(DefaultTableModel)trix2.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getId(),lista.get(i).getPreco(),lista.get(i).getNome(),lista.get(i).getQuantidade(),lista.get(i).getMes()});
            
    }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField t1;
    private javax.swing.JTable trix1;
    private javax.swing.JTable trix2;
    // End of variables declaration//GEN-END:variables
}
