/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Declaracao_Compra extends javax.swing.JInternalFrame {

    /**
     * Creates new form Desmarca_Consultas
     */
    public Declaracao_Compra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        trix = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jButton1.setText("Mostra todo estoque");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 30, 200, 23);

        trix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id produto", "Nome Produto", "Categoria"
            }
        ));
        jScrollPane3.setViewportView(trix);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(250, 80, 730, 90);

        jLabel1.setText("ID do produto:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 200, 120, 30);
        getContentPane().add(t1);
        t1.setBounds(380, 200, 190, 30);

        jLabel2.setText("Nome do Produto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 240, 120, 30);
        getContentPane().add(t2);
        t2.setBounds(380, 240, 190, 30);

        jLabel8.setText("Categoria:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 280, 60, 20);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico", "Alimenticio", "Limpeza" }));
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        getContentPane().add(c1);
        c1.setBounds(380, 280, 170, 20);

        jLabel3.setText("Quantidade da compra");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 310, 140, 30);
        getContentPane().add(t3);
        t3.setBounds(380, 310, 190, 30);

        jLabel9.setText("Mes da compra");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 360, 140, 20);

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        c2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c2ItemStateChanged(evt);
            }
        });
        getContentPane().add(c2);
        c2.setBounds(380, 360, 170, 20);

        jLabel4.setText("Preço pago:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(610, 200, 120, 30);
        getContentPane().add(t4);
        t4.setBounds(730, 200, 190, 30);

        jButton2.setText("Cadastrar  declaração");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 270, 200, 23);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents
String categoria ="";
String mes="";
int qtd2=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       listaTodo5();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String id = t1.getText(), nome = t2.getText();
      int qtd = Integer.parseInt(t3.getText());
      float preco = Float.parseFloat(t4.getText());
      ClinicaDao c= new ClinicaDao();
     String resp = c.gravadecla(id, nome, categoria, qtd, mes, preco);
      qtd2=qtd+c.pegar(id,nome);
      c.updateestado(id, qtd2,nome);
      if(resp == "ok"){
                            JOptionPane.showMessageDialog(null, "Dados foram Cadastrados");
                            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
        categoria = (String) c1.getSelectedItem();
    }//GEN-LAST:event_c1ItemStateChanged

    private void c2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c2ItemStateChanged
        mes = (String) c2.getSelectedItem();
    }//GEN-LAST:event_c2ItemStateChanged
public void listaTodo5(){
         ArrayList <Produtos> lista=new ClinicaDao().listarFunc17();
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getId(),lista.get(i).getNome(),lista.get(i).getCategoria()});
            
    }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable trix;
    // End of variables declaration//GEN-END:variables
}
