/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Demitir_Funcionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Desmarca_Consultas
     */
    public Demitir_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        trix = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Funcionario :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 60, 190, 30);
        getContentPane().add(t1);
        t1.setBounds(460, 60, 190, 30);

        jButton1.setText("Mostrar Funcionario pelo RG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 60, 200, 30);

        jLabel2.setText("RG Funcionario que deseja Demitir");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 260, 250, 30);
        getContentPane().add(t2);
        t2.setBounds(500, 260, 190, 30);

        jButton2.setText("Desmarca Demitir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 260, 200, 30);

        trix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RG", "Nome", "Idade", "Salario", "Email", "Sexo", "cargo"
            }
        ));
        jScrollPane4.setViewportView(trix);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(260, 110, 730, 110);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rg=t1.getText();
        listaTodos(rg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClinicaDao D= new ClinicaDao();
        String resp = D.deleteF(t2.getText());
        if (resp.equals("ok")) {
            JOptionPane.showMessageDialog(null, "dados deletados");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void listaTodos(String Placa){
         ArrayList <Funcionario> lista=new ClinicaDao().listarFunc14(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getSalario(),lista.get(i).getEmail(),lista.get(i).getSexo(),lista.get(i).getCargo()});
            
    }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable trix;
    // End of variables declaration//GEN-END:variables
}
