/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Desmarca_Consultas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Desmarca_Consultas
     */
    public Desmarca_Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        trix = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Paciente :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 10, 180, 30);
        getContentPane().add(t1);
        t1.setBounds(430, 10, 190, 30);

        jButton1.setText("Mostrar Consultas Marcas pelo RG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 10, 280, 30);

        trix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RG", "Nome", "Data", "Hora", "Idade", "Nome do medico", "Especialidade", "Tipo de consulta", "ID_Consulta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(trix);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 70, 880, 120);

        jLabel2.setText("ID Consulta que deseja  Desmarca");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 230, 240, 30);
        getContentPane().add(t2);
        t2.setBounds(460, 230, 190, 30);

        jButton2.setText("Desmarca Consulta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 230, 200, 30);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rg=t1.getText();
            listaTodos(rg);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClinicaDao D= new ClinicaDao();
        String resp = D.deletev(t2.getText());
        if (resp.equals("ok")) {
            JOptionPane.showMessageDialog(null, "dados deletados");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
public void listaTodos(String Placa){
         ArrayList <Consulta> lista=new ClinicaDao().listarFunc6(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getData(),lista.get(i).getHora(),lista.get(i).getIdade(),lista.get(i).getMedico(),lista.get(i).getEspecialidade(),lista.get(i).getTipo(),lista.get(i).getId()});
            
    }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable trix;
    // End of variables declaration//GEN-END:variables
}
