/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author guima
 */
public class Login extends javax.swing.JFrame {


    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jt2 = new javax.swing.JTextField();
        jt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 110, 30);

        l1.setText("Usuario:");
        getContentPane().add(l1);
        l1.setBounds(30, 50, 110, 30);
        getContentPane().add(jt2);
        jt2.setBounds(140, 100, 250, 30);
        getContentPane().add(jt1);
        jt1.setBounds(140, 50, 250, 30);

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 190, 63, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_ciaclinic/Image/Sem título.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 264, 60, 36);

        jMenu1.setText("Mais Opçoes");

        jMenuItem1.setText("Alterar Senha");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 527, 365);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String valor = jt2.getText();
        ClinicaDao c = new ClinicaDao();
        String resposta = c.consultar(jt1.getText(),valor);
        String nome = c.consultarnome(jt1.getText(),valor);
        JFrame Tela=null;
        java.util.Date data = new java.util.Date();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(data.getTime());
        Entrada_Saida e=new Entrada_Saida(jt1.getText(),timestamp);
        String resposta2 = c.consultarrr(jt1.getText(), valor);
        
        if(resposta == null){
            JOptionPane.showMessageDialog(this, "acesso negado");
            return;
            }    
        if(resposta2.equals("Contratado")){
            if(resposta.equals("Medico")){
            Tela =new Tela_Medico();
                JOptionPane.showMessageDialog(this,"Bem vindo "+ nome);
                c.gravarEntrada(e);
                Tela.setLocationRelativeTo(null);
            Tela.setVisible(true);
            }
            else if(resposta.equals("Gerente")){
             Tela =new Tela_Gerente();
                JOptionPane.showMessageDialog(this,"Bem vindo "+ nome);
                c.gravarEntrada(e);
                Tela.setLocationRelativeTo(null);
                 Tela.setVisible(true);
            }
            else if(resposta.equals("Atendente")){
            Tela =new Tela_Atendente();
                JOptionPane.showMessageDialog(this,"Bem vindo "+ nome);
                c.gravarEntrada(e);
                Tela.setLocationRelativeTo(null);
                Tela.setVisible(true);
            }
        }
        else{
        JOptionPane.showMessageDialog(null, "Esse funcionario foi demitido");
        }
        /*switch(resposta2){
                case "Contratado": 
        switch (resposta) {
            case "Medico":
                Tela =new Tela_Medico();
                JOptionPane.showMessageDialog(this,"Bem vindo "+ nome);
                c.gravarEntrada(e);
                Tela.setLocationRelativeTo(null);
            Tela.setVisible(true);
                break;
            case "Gerente":
                Tela =new Tela_Gerente();
                JOptionPane.showMessageDialog(this,"Bem vindo "+ nome);
                c.gravarEntrada(e);
                Tela.setLocationRelativeTo(null);
                 Tela.setVisible(true);
                break;
            case "Atendente":
                Tela =new Tela_Atendente();
                JOptionPane.showMessageDialog(this,"Bem vindo "+ nome);
                c.gravarEntrada(e);
                Tela.setLocationRelativeTo(null);
                Tela.setVisible(true);
                break;       
        }
        break;
        
               case "Demitido":
                   JOptionPane.showMessageDialog(null, "Esse funcionario foi demitido");
                   break;
                    
            }*/
            
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/projeto_ciaclinic/Image/Sem título.png")));
    }
}
