/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Mostrar_Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Controle_Entrada_Saida_Funcionario
     */
    public Mostrar_Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        trix = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        p1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Funcionario :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 60, 120, 30);
        getContentPane().add(t1);
        t1.setBounds(410, 60, 190, 30);

        trix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RG", "Nome", "Idade", "Salario", "Email", "Sexo", "cargo"
            }
        ));
        jScrollPane4.setViewportView(trix);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(280, 320, 730, 110);

        jButton2.setText("Mostrar Funcionario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 60, 140, 30);

        p1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar por Sexo"));
        p1.setLayout(null);

        jLabel11.setText("Plano de saude ou Particular");
        p1.add(jLabel11);
        jLabel11.setBounds(20, 190, 240, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Feminino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        p1.add(jRadioButton1);
        jRadioButton1.setBounds(20, 60, 140, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Masculino ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        p1.add(jRadioButton2);
        jRadioButton2.setBounds(20, 30, 140, 23);

        getContentPane().add(p1);
        p1.setBounds(340, 150, 200, 110);

        p2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostrar por cargo"));
        p2.setLayout(null);

        jLabel12.setText("Plano de saude ou Particular");
        p2.add(jLabel12);
        jLabel12.setBounds(20, 190, 240, 30);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Gerente");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        p2.add(jRadioButton3);
        jRadioButton3.setBounds(20, 90, 140, 23);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Atendente");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        p2.add(jRadioButton4);
        jRadioButton4.setBounds(20, 30, 140, 23);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Medico");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        p2.add(jRadioButton5);
        jRadioButton5.setBounds(20, 60, 140, 23);

        getContentPane().add(p2);
        p2.setBounds(560, 150, 200, 130);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents
String sexo="";
String cargo="";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String rg=t1.getText();
        listaTodos(rg);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        sexo="Masculino"; 
        listaTodos2(sexo);
        p2.setEnabled(false);
         
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        sexo="Feminino"; 
        listaTodos2(sexo);
        p2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        cargo="Atendente";
        listaTodos3(cargo);
        p2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
         cargo="Medico";
        listaTodos3(cargo);
        p2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
         cargo="Gerente";
        listaTodos3(cargo);
        p2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed
public void listaTodos(String Placa){
         ArrayList <Funcionario> lista=new ClinicaDao().listarFunc14(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getSalario(),lista.get(i).getEmail(),lista.get(i).getSexo(),lista.get(i).getCargo()});
            
    }}
public void listaTodos2(String Placa){
         ArrayList <Funcionario> lista=new ClinicaDao().listarFunc15(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getSalario(),lista.get(i).getEmail(),lista.get(i).getSexo(),lista.get(i).getCargo()});
            
    }}
public void listaTodos3(String Placa){
         ArrayList <Funcionario> lista=new ClinicaDao().listarFunc16(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getSalario(),lista.get(i).getEmail(),lista.get(i).getSexo(),lista.get(i).getCargo()});
            
    }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JTextField t1;
    private javax.swing.JTable trix;
    // End of variables declaration//GEN-END:variables
}
