/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Mostrar_Dados_Paciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public Mostrar_Dados_Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        trix = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Medico = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtalergia = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("RG Do Paciente :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 120, 140, 30);
        getContentPane().add(t1);
        t1.setBounds(480, 120, 190, 30);

        trix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "RG", "Nome", "Idade", "Nome do medico", "Especialidade", "Sexo", "Diagnostico"
            }
        ));
        jScrollPane1.setViewportView(trix);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 340, 590, 140);

        jButton1.setText("Mostrar Consultas Marcas pelo RG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 120, 200, 30);

        Medico.setBorder(javax.swing.BorderFactory.createTitledBorder("Medico"));
        Medico.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Medico.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MedicoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Medico);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(530, 160, 140, 150);

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Especialidade"));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(370, 160, 140, 150);

        txtdesc.setColumns(20);
        txtdesc.setRows(5);
        txtdesc.setText("Descrição Medica");
        jScrollPane4.setViewportView(txtdesc);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(180, 180, 166, 140);

        txtalergia.setColumns(20);
        txtalergia.setRows(5);
        txtalergia.setText("Alergias");
        jScrollPane5.setViewportView(txtalergia);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(690, 190, 166, 140);

        setBounds(0, 0, 1365, 730);
    }// </editor-fold>//GEN-END:initComponents
String especialidade="";
String medico="";
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        listaTodos();
        listaTodos2();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        especialidade = jList2.getSelectedValue();
        listaTodos5();
        listaTodo(especialidade);
    }//GEN-LAST:event_jList2ValueChanged

    private void MedicoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MedicoValueChanged
        medico = Medico.getSelectedValue();
        listaTodo2(medico);
    }//GEN-LAST:event_MedicoValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClinicaDao D= new ClinicaDao();
        listaTodo4(t1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed
public void listaTodos() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc();
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addElement(lista.get(i).getEspecialidade());
        }
        jList2.setModel(modelo);
    }
public void listaTodos2() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc2();
        DefaultListModel modelo2 = new DefaultListModel();
        for (int i = 0; i < lista.size(); i++) {
            modelo2.addElement(lista.get(i).getNome());
        }
        Medico.setModel(modelo2);
    }
public void listaTodos5() {
        ArrayList<Medico> lista = new ClinicaDao().listarFunc5(especialidade);
        DefaultListModel modelo4 = new DefaultListModel();

        for (int i = 0; i < lista.size(); i++) {
            modelo4.addElement(lista.get(i).getNome());
        }
        Medico.setModel(modelo4);
    }
public void listaTodo(String Placa){
            String str="";
            String str1="";
            
         ArrayList <Paciente> lista=new ClinicaDao().listarFunc9(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getMedico(),lista.get(i).getEspecialidade(),lista.get(i).getSexo(),lista.get(i).getDiagnostico()});
            str += "alergias:"+lista.get(i).getAlergia()+"\n";
            str1 += "descrições medicas:"+lista.get(i).getDescricao()+"\n";
    }
            txtalergia.setText(str);
            txtdesc.setText(str1);
}
public void listaTodo2(String Placa){
            String str="";
            String str1="";
         ArrayList <Paciente> lista=new ClinicaDao().listarFunc10(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getMedico(),lista.get(i).getEspecialidade(),lista.get(i).getSexo(),lista.get(i).getDiagnostico()});
            str += "alergias:"+lista.get(i).getAlergia()+"\n";
            str1 += "descrições medicas:"+lista.get(i).getDescricao()+"\n";
            
    }
txtalergia.setText(str);
            txtdesc.setText(str1);
}
public void listaTodo4(String Placa){
    String str="";
            String str1="";
         ArrayList <Paciente> lista=new ClinicaDao().listarFunc11(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getRg(),lista.get(i).getNome(),lista.get(i).getIdade(),lista.get(i).getMedico(),lista.get(i).getEspecialidade(),lista.get(i).getSexo(),lista.get(i).getDiagnostico()});
            str += "alergias:"+lista.get(i).getAlergia()+"\n";
            str1 += "descrições medicas:"+lista.get(i).getDescricao()+"\n";
            
    }
            txtalergia.setText(str);
            txtdesc.setText(str1);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Medico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField t1;
    private javax.swing.JTable trix;
    private javax.swing.JTextArea txtalergia;
    private javax.swing.JTextArea txtdesc;
    // End of variables declaration//GEN-END:variables
}
