/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guima
 */
public class Mostrar_Esttoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public Mostrar_Esttoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        trix = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        T1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        trix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id PRODUTO", "Nome produto", "Categoria", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(trix);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 230, 610, 240);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 150, 110, 40);
        getContentPane().add(T1);
        T1.setBounds(400, 50, 200, 30);

        jLabel1.setText("Digite o id do produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 50, 120, 30);

        setBounds(0, 0, 1365, 768);
    }// </editor-fold>//GEN-END:initComponents
    ClinicaDao c = new ClinicaDao();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String id = T1.getText();
       listaTodo4(id);
       
        
    }//GEN-LAST:event_jButton1ActionPerformed
public void listaTodo4(String Placa){
         ArrayList <Produtos> lista=new ClinicaDao().listarFunc18(Placa);
         DefaultTableModel modelo=(DefaultTableModel)trix.getModel();
         modelo.setNumRows(0);
         for(int i=0;i<lista.size();i++){
         modelo.addRow(new Object[]{lista.get(i).getId(),lista.get(i).getNome(),lista.get(i).getCategoria(),lista.get(i).getQuantidade()});
            
    }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField T1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trix;
    // End of variables declaration//GEN-END:variables
}
