/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_ciaclinic;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;

/**
 *
 * @author guima
 */
public class Tela_Gerente extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Atendente
     */
    public Tela_Gerente() {
        initComponents();
        redimensionarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Gerente");
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 840, 420);

        jMenu3.setText("Questoes de trabalho");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Bate ponto saida");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar2.add(jMenu3);

        jMenu1.setText("Controle Saida e entrada Funcionario");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem12.setText("Controle Saida e entrada Funcionario");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Estoque");

        jMenuItem4.setText("Exibir Estoque");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem8.setText("Cadastrar Novo produto no estoque");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar2.add(jMenu2);

        jMenu5.setText("Funcionario");

        jMenuItem6.setText("Mostrar Funcionarios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem9.setText("Cadastrar Funcionario");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Adicionar novas especialidades para medicos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem13.setText("Mudar Status Funcionario");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem11.setText("Demitir Funcionario");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar2.add(jMenu5);

        jMenu7.setText("Financeiro");

        jMenuItem1.setText("Controle de gasto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuItem5.setText("Declaração de compra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        setBounds(0, 0, 864, 488);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        saida v = new saida();
        v.setTitle("Bate Ponto saida");
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Mostrar_Esttoque v = new Mostrar_Esttoque();
        v.setTitle("Mostrar estoque");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       Controle_Entrada_Saida_Funcionario v = new Controle_Entrada_Saida_Funcionario();
        v.setTitle("Mostrar Consultas");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
         Cad_Produto_estoque v = new Cad_Produto_estoque();
        v.setTitle("Cadastra novo produto");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Mostrar_Funcionarios v = new Mostrar_Funcionarios();
        v.setTitle("Mostrar funcionario");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
         Cad_Dados_Funcionario v = new Cad_Dados_Funcionario();
        v.setTitle("Contratar funcionario");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Demitir_Funcionario v = new Demitir_Funcionario();
        v.setTitle("Demitir funcionario");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Controle_Financeiro v = new Controle_Financeiro();
        v.setTitle("Controle financeiro");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Declaracao_Compra v = new Declaracao_Compra();
        v.setTitle("Declaração de compra");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Cad_espec_medico v = new Cad_espec_medico();
        v.setTitle("Cadastra nova especialidade medica");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Alterar_Funcionario1 v = new Alterar_Funcionario1();
        v.setTitle("Alterar Status do Funcionario");
        v.setVisible(true);
        jDesktopPane1.add(v);
        JInternalFrame[] frames = jDesktopPane1.getAllFrames();
      if ( frames.length == 0) return;
          else cascata( frames, jDesktopPane1.getBounds(), 25 );
    }//GEN-LAST:event_jMenuItem13ActionPerformed
private void cascata( javax.swing.JInternalFrame[] frames,
                                java.awt.Rectangle retangulo, int separacao ) {
    // a "margem" depende da quantidade de janelas internas criadas
    // a “separacao” foi definida em 25 pontos
    // “retangulo” está definido pelo tamanho/posição de jDesktopPane1
    int margem = frames.length * separacao + separacao;
    int width = retangulo.width - margem;
    int height = retangulo.height - margem;
    for ( int i = 0; i < frames.length; i++) {
        frames[i].setBounds( separacao + retangulo.x + i*separacao,
                             separacao + retangulo.y + i*separacao,
                             width, height );
        jDesktopPane1.moveToFront(frames[i]); //janela na frente
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Gerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

    private void redimensionarTela() {
       Toolkit t = Toolkit.getDefaultToolkit();
        Dimension dimensao = t.getScreenSize();
        this.setSize((dimensao.width + 5), (dimensao.height - 38));
        jDesktopPane1.setSize((dimensao.width + 5), (dimensao.height - 38));
        
    }
}
